import type { Metadata } from "next";
import "./globals.css";
import AppSidebar from "@/components/Sidebar/AppSidebar";
import { SidebarProvider } from "@/components/ui/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="sm:flex h-screen text-white">
        <SidebarProvider>
          <AppSidebar />
          <main className="grow bg-custom-gradient2 text-white">
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
